# Generated by Django 5.1.6 on 2025-02-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_last_interest_calculation_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='loan_duration',
            field=models.IntegerField(default=12, help_text='Duration in months'),
        ),
        migrations.AddField(
            model_name='account',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
