# Generated by Django 5.1.6 on 2025-02-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_loan_duration_account_return_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='loan_duration',
        ),
        migrations.RemoveField(
            model_name='account',
            name='return_date',
        ),
        migrations.AddField(
            model_name='loan',
            name='duration_months',
            field=models.IntegerField(default=0, help_text='Duration in months'),
        ),
        migrations.AddField(
            model_name='loan',
            name='duration_years',
            field=models.IntegerField(default=0, help_text='Duration in years'),
        ),
    ]
