# Generated by Django 5.1.6 on 2025-02-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_loan_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='duration_years',
        ),
        migrations.AlterField(
            model_name='loan',
            name='duration_months',
            field=models.IntegerField(default=12, help_text='Duration in months (e.g., 12, 18, 24)'),
        ),
    ]
